version: '2.0'
services:
  nginx:
    image: bitnami/nginx:latest
    networks:
      - app-tier
    depends_on:
      - php
    ports:
      - 8000:8080
    volumes:
      - ./deployment/docker/nginx/basketFinder.conf:/opt/bitnami/nginx/conf/vhosts/basketFinder.conf
      - ./api:/app

  php:
    build: deployment/docker/php
    networks:
      - app-tier
    depends_on:
      - mysql
    volumes:
      - './api:/app'

  mysql:
    image: 'bitnami/mysql:5.7'
    networks:
      - app-tier
    ports:
      - 3307:3306
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MYSQL_DATABASE=basketFinder
      - MYSQL_USER=basketFinder
      - MYSQL_PASSWORD=basketFinder
      - MYSQL_ROOT_PASSWORD=mysecretpw
      - MYSQL_PORT=3306

  node:
    image: bitnami/node
    command: "sh -c 'npm install && npm start'"
    ports:
      - 3000:3000
    volumes:
      - ./web:/app

networks:
  app-tier:
    driver: bridge
